### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by yehia** [adminfaces/admin-starter-springboot#13]
Hello, i have this error:

`java.lang.IllegalArgumentException: Unable to create WebResourceSet from [C:\Users\Yehia%20Azanki\.m2\repository\org\glassfish\javax.faces\2.3.4\javax.faces-2.3.4.jar]
	at org.apache.catalina.webresources.StandardRoot.createWebResourceSet(StandardRoot.java:419) ~[tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.joinfaces.autoconfigure.tomcat.JsfTomcatApplicationListener.addClasspathResourceSets(JsfTomcatApplicationListener.java:194) ~[joinfaces-autoconfigure-3.2.6.jar:3.2.6]
	at org.joinfaces.autoconfigure.tomcat.JsfTomcatApplicationListener.onApplicationEvent(JsfTomcatApplicationListener.java:163) ~[joinfaces-autoconfigure-3.2.6.jar:3.2.6]
	at org.joinfaces.autoconfigure.tomcat.JsfTomcatApplicationListener.onApplicationEvent(JsfTomcatApplicationListener.java:41) ~[joinfaces-autoconfigure-3.2.6.jar:3.2.6]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:400) ~[spring-context-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:354) ~[spring-context-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.boot.context.event.EventPublishingRunListener.running(EventPublishingRunListener.java:103) ~[spring-boot-2.0.6.RELEASE.jar:2.0.6.RELEASE]
	at org.springframework.boot.SpringApplicationRunListeners.running(SpringApplicationRunListeners.java:78) ~[spring-boot-2.0.6.RELEASE.jar:2.0.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:323) [spring-boot-2.0.6.RELEASE.jar:2.0.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1242) [spring-boot-2.0.6.RELEASE.jar:2.0.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1230) [spring-boot-2.0.6.RELEASE.jar:2.0.6.RELEASE]
	at com.github.adminfaces.starter.AdminBootMain.main(AdminBootMain.java:30) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_241]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_241]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_241]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_241]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) [spring-boot-devtools-2.0.6.RELEASE.jar:2.0.6.RELEASE]`

**Comment by rmpestano** [comment]
Sorry I cannot reproduce, I just run the application with both java -jar and spring-boot maven plugin and it just works. 
<img width="1674" alt="Screenshot 2020-05-26 at 15 50 08" src="https://user-images.githubusercontent.com/1592273/82908760-ba588500-9f68-11ea-8d28-22e3d1ff009c.png">
